export {default as HomeScreen} from './main/home';
export {default as UserSettingScreen} from './main/user-setting/UserSettingScreen';
export {default as DiscoverScreen} from './main/discover/DiscoverScreen';
export {default as LibraryScreen} from './main/library/LibraryScreen';
export {default as UserDetailScreen} from './main/user-detail-screen/UserDetailScreen';
export {default as PlayScreen} from './main/play-kahoot/PlayScreen';
export {default as ResultPlayKahoot} from './main/result-play-kahoot/ResultPlayKahoot';
export {default as ReportDetailScreen} from './main/report-detail-screen/ReportDetailScreen';
export {default as JoinScreen} from './main/join/JoinScreen';
export {default as SearchKahootScreen} from './main/search-kahoot-screen/SearchKahootScreen';
export * from './main/question';
export * from './main/setting-question';
export * from './main/create-question';
// Auth
export * from './auth/login';
export * from './auth/register';
export * from './auth/forgot';
export * from './auth/otp';
export * from './auth/resetpassword';
export * from './loading';
