// Generated by https://quicktype.io

export interface SearchResponse {
  code: number;
  success: boolean;
  data: SearchData;
  message: string;
}

export interface SearchData {
  users: User[];
  kahoots: Kahoot[];
}

export interface Kahoot {
  id: number;
  coverImage: null;
  title: string;
  createdAt: number;
  visibleScope: string;
  userId: number;
  username: string;
  userImage: string;
  numberOfQuestion: number;
}

export interface User {
  id: number;
  username: string;
  name: string;
  image: string;
}
